/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.AGREGAR;

import Clases.Item;
import GUI.MenuPrincipal;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Felipe
 */
public class FormAgregarAdjudicacion extends javax.swing.JFrame {

    private static FormAgregarAdjudicacion instancia;
    /**
     * Creates new form FormAgregarPostulacion
     */
    public FormAgregarAdjudicacion() {
        initComponents();
    }
    
    public static FormAgregarAdjudicacion getInstancia() {
        if(instancia == null)
        {
            instancia = new FormAgregarAdjudicacion();
        }
        
        return instancia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Proyecto = new javax.swing.JLabel();
        investigadorBox = new javax.swing.JComboBox<>();
        proyectoBox = new javax.swing.JComboBox<>();
        agregarPostulacion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        montoText = new javax.swing.JTextField();
        fechaadjudicacion = new com.toedter.calendar.JDateChooser();
        fechatermino = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("Postulante: ");

        Proyecto.setText("Proyecto:");

        agregarPostulacion.setText("Agregar adjudicación");
        agregarPostulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarPostulacionActionPerformed(evt);
            }
        });

        jLabel2.setText("Monto ajudicado:");

        jLabel3.setText("Fecha de adjudicación");

        jLabel4.setText("Fecha de término");

        montoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montoTextActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Agregar adjudicación");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(agregarPostulacion)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Proyecto)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(proyectoBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(investigadorBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fechaadjudicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fechatermino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(montoText)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel5)))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(investigadorBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Proyecto)
                    .addComponent(proyectoBox, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(montoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(fechaadjudicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(fechatermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(agregarPostulacion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try{
            MenuPrincipal.Conexion();  
            Statement s = MenuPrincipal.connection.createStatement();
            
            // AGREGA OPCIONES AL COMBOBOX DE INVESTIGADOR
            investigadorBox.removeAllItems();
            ResultSet resultInvestigador = s.executeQuery("SELECT nombreInvestigador, RUT FROM INVESTIGADOR");
            while(resultInvestigador.next())
            {
                investigadorBox.addItem(new Item(resultInvestigador.getString("RUT"), resultInvestigador.getString("nombreInvestigador")+": "+resultInvestigador.getString("RUT")));
            }   
            
            // AGREGA OPCIONES AL COMBOBOX DE PROYECTO
            proyectoBox.removeAllItems();
            ResultSet resultProyecto = s.executeQuery("SELECT codigoproyecto, titulo FROM PROYECTO");
            while(resultProyecto.next())
            {
                proyectoBox.addItem(new Item(resultProyecto.getString("codigoProyecto"), resultProyecto.getString("titulo")));
            }

        }
        catch(Exception e){
                    JOptionPane.showMessageDialog(this, e.getMessage());    
        }
        
        
    
    }//GEN-LAST:event_formWindowActivated

    private void agregarPostulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarPostulacionActionPerformed
        
        // OBTIENE EL RUT DEL INVESTIGADOR
            String rutT = ((Item)investigadorBox.getSelectedItem()).getIdString();
           
            
            // OBTIENE EL CÓDIGO DE PROYECTO QUE SE ADJUDICA
            String codProyecto = ((Item)proyectoBox.getSelectedItem()).getIdString();
        
        try{
            
            
            // MONTO
            String montoAdjudicado = montoText.getText();
            
            
            // FECHAS
            String fechainicio;
            String fechadetermino;
            
            if(DateFormat.getDateInstance().format(fechaadjudicacion.getDate()) != null)
            {
                fechainicio = DateFormat.getDateInstance().format(fechaadjudicacion.getDate());
            } else{ fechainicio = "hola";}
            
            if(DateFormat.getDateInstance().format(fechatermino.getDate()) != null)
            {
                fechadetermino = DateFormat.getDateInstance().format(fechatermino.getDate());
            } else { fechadetermino = "hola"; }
            
            if(fechaadjudicacion.getDate().after(fechatermino.getDate()))
            {
                JOptionPane.showMessageDialog(this, "La fecha de término debe ser posterior a la fecha de adjudicación");
            }
            else
            {
                Statement s = MenuPrincipal.connection.createStatement();
            
                int z = s.executeUpdate("INSERT INTO ADJUDICA(codigoproyecto, RUT, montoadjudicado, fechaadjudicacion, fechadetermino) values("
                +codProyecto+", "+"'"+rutT+"'"+", "+montoAdjudicado+", "+"'"+fechainicio+"'"+", "+"'"+fechadetermino+"'"+")");
            
                if(z==1){ JOptionPane.showMessageDialog(this, "Se agregó la adjudicación exitosamente");  }
            }
            
            
                     
            
               
        }
        catch(SQLException e){
                 
            System.out.println(e.getSQLState());
                 if(e.getSQLState().equals("23505"))
                 {
                     JOptionPane.showMessageDialog(this, "No se puede agregar la adjudicación debido a que ya existe una con las claves foráneas: "
                     + rutT+" y "+codProyecto);
                 }  
                 else if(e.getSQLState().equals("42703"))
                 {
                     JOptionPane.showMessageDialog(this, "Monto inválido, por favor ingrese un número sin puntos ni otros caracteres");
                 }
                 else if(e.getSQLState().equals("42601"))
                 {
                     JOptionPane.showMessageDialog(this, "LLene campos vacíos");
                 }
        }
    }//GEN-LAST:event_agregarPostulacionActionPerformed

    private void montoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_montoTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAgregarPostulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAgregarPostulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAgregarPostulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAgregarPostulacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAgregarPostulacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Proyecto;
    private javax.swing.JButton agregarPostulacion;
    private com.toedter.calendar.JDateChooser fechaadjudicacion;
    private com.toedter.calendar.JDateChooser fechatermino;
    private javax.swing.JComboBox<Item> investigadorBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField montoText;
    private javax.swing.JComboBox<Item> proyectoBox;
    // End of variables declaration//GEN-END:variables
}
