package GUI.AGREGAR;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JComboBox;

import Clases.Item;
import GUI.MenuPrincipal;
/**
 *
 * @author Felipe
 */
public class FormAgregarInvestigador extends javax.swing.JFrame {

    private static FormAgregarInvestigador instancia;
    
    public FormAgregarInvestigador() {
        initComponents();
    }
    
    public static FormAgregarInvestigador getInstancia() {
        if(instancia == null)
        {
            instancia = new FormAgregarInvestigador();
        }
        
        return instancia;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        rutText = new javax.swing.JTextField();
        nombreinvText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        calleText = new javax.swing.JTextField();
        numText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        centroDeInvestigacionBox = new javax.swing.JComboBox<Item>();
        rolBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        universidadBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        ciudadBox = new javax.swing.JComboBox<>();
        categoriaBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        rutText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rutTextActionPerformed(evt);
            }
        });

        jButton1.setText("Insertar registro");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("RUT");

        jLabel2.setText("Nombre");

        jLabel4.setText("Categoría");

        jLabel5.setText("Calle");

        jLabel6.setText("Número");

        jLabel7.setText("Centro Inv");

        centroDeInvestigacionBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                centroDeInvestigacionBoxActionPerformed(evt);
            }
        });

        jLabel8.setText("Rol");

        jLabel9.setText("Universidad");

        jLabel10.setText("Ciudad");

        ciudadBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciudadBoxActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Ingresar Investigador");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 267, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel10)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(centroDeInvestigacionBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(99, 99, 99)
                                .addComponent(jLabel8)
                                .addGap(45, 45, 45)
                                .addComponent(rolBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rutText, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(calleText, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(universidadBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(categoriaBox, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numText, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ciudadBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreinvText, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rutText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombreinvText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ciudadBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(categoriaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(calleText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(numText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(centroDeInvestigacionBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(rolBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(universidadBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String rut = rutText.getText();
        String nombreinv = nombreinvText.getText();                      
                       
        String calle = calleText.getText();            
        String num = numText.getText(); 
        try{
            
            MenuPrincipal.Conexion();
       
            // TABLAS DE INVESTIGADOR
            
             
            
            // ciudad en la que vive el investigador
            String codigociudad = ((Item)ciudadBox.getSelectedItem()).getIdString();
            
            // categoría del investigador
            String codigocategoria = ((Item)categoriaBox.getSelectedItem()).getIdString();
            
            Statement s = MenuPrincipal.connection.createStatement();
            
            int z=0;
            if(rut.length()==0 || nombreinv.length()==0 || calle.length()==0 || num.length()==0)
            {
                JOptionPane.showMessageDialog(this, "Llena campos vacíos");
            }
            else
            {
                //crea investigador con los datos proporcionados
            z = s.executeUpdate("INSERT INTO INVESTIGADOR(RUT, nombreInvestigador, codigociudad, codigocategoria, calle, num) values ('"
            +rut+"', '"+nombreinv+"', "+codigociudad+", "+codigocategoria+", '"+calle+"', "+num+")");
            }
            
                        
            // ASOCIA (O NO) AL INVESTIGADOR CON EL CENTRO DE INVESTIGACIÓN
            Item CISeleccionado = (Item)centroDeInvestigacionBox.getSelectedItem();
            Item rolSeleccionado = (Item)rolBox.getSelectedItem();
            
            if(!CISeleccionado.getName().equals("No asociar ningún centro"))
            {
                int x = s.executeUpdate("INSERT INTO TRABAJACI(rut, codigoCI, codigorol) values ("
                +rut+", "+CISeleccionado.getId() + ", " + rolSeleccionado.getId() + ")");             
            }
            
            // ASOCIA (O NO) AL INVESTIGADOR CON ALGUNA UNIVERSIDAD
            Item universidadSeleccionada = (Item)universidadBox.getSelectedItem();
            if(!universidadSeleccionada.getName().equals("No asociar a universidad"))
            {
                
                int y = s.executeUpdate("INSERT INTO PERTENECEUNIVERSIDAD(rut, codigouniversidad) values ("
                +rut + ", "+universidadSeleccionada.getId()+")");
            }
            
         
            if(z == 1){ JOptionPane.showMessageDialog(this, "Se agregó el investigador (y asociaciones) exitosamente");  }
            
            
        } catch(SQLException e){
                 
            System.out.println(e.getSQLState());
                 if(e.getSQLState().equals("23505"))
                 {
                     JOptionPane.showMessageDialog(this, "No se puede agregar la investigadora(o) debido a que ya existe una(o) con el rut: "
                     + rut);
                 }  
                 else if(e.getSQLState().equals("42703"))
                 {
                     JOptionPane.showMessageDialog(this, "Número telefónico inválido, por favor ingrese un número sin puntos ni otros caracteres");
                 }  
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rutTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rutTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rutTextActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void centroDeInvestigacionBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_centroDeInvestigacionBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_centroDeInvestigacionBoxActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
        try{
            MenuPrincipal.Conexion();  
            Statement s = MenuPrincipal.connection.createStatement();
            
            // AGREGA OPCIONES AL COMBOBOX DE CIUDAD
            ResultSet resultCiudad = s.executeQuery("SELECT nombreciudad, codigociudad FROM CIUDAD");
            ciudadBox.removeAllItems();
            while(resultCiudad.next())
            {
                ciudadBox.addItem(new Item(resultCiudad.getString("codigociudad"), resultCiudad.getString("nombreciudad")));
            }   
            
            // AGREGA OPCIONES AL COMBOBOX DE CATEGORÍA
            ResultSet resultCategoría = s.executeQuery("SELECT codigocategoria, descripcioncategoría FROM categoria");
            categoriaBox.removeAllItems();
            while(resultCategoría.next())
            {
                categoriaBox.addItem(new Item(resultCategoría.getString("codigocategoria"), resultCategoría.getString("descripcioncategoría")));
            }
            
            // AGREGA OPCIONES AL COMBOBOX DE CENTRO DE INVESTIGACIÓN            
            ResultSet resultCI = s.executeQuery("SELECT nombre, codigoCI FROM CENTRODEINVESTIGACION"); 
            centroDeInvestigacionBox.removeAllItems();
            centroDeInvestigacionBox.addItem(new Item(0, "No asociar ningún centro"));
            while(resultCI.next())
            {
                centroDeInvestigacionBox.addItem(new Item(Integer.parseInt(resultCI.getString("codigoCI")), resultCI.getString("nombre")));
                
            }
            
            //AGREGA OPCIONES AL COMBOBOX DE ROL EN CENTRO DE INVESTIGACIÓN
            rolBox.removeAllItems();
            ResultSet resultRol = s.executeQuery("SELECT codigorol, descripcionrol FROM rol");
            while(resultRol.next())
            {
                rolBox.addItem(new Item(Integer.parseInt(resultRol.getString("codigorol")), resultRol.getString("descripcionrol")));
            }
            
            // AGREGA OPCIONES AL COMBOBOX DE UNIVERSIDAD
            ResultSet resultUniversidad = s.executeQuery("SELECT codigouniversidad, nombre FROM UNIVERSIDAD");
            universidadBox.removeAllItems();
            universidadBox.addItem(new Item(0, "No asociar a universidad"));
            while(resultUniversidad.next())
            {
                universidadBox.addItem(new Item(Integer.parseInt(resultUniversidad.getString("codigouniversidad")), resultUniversidad.getString("nombre")));
            }
            
            
            
        
        }
        catch(Exception e){
                    JOptionPane.showMessageDialog(this, e.getMessage());    
        }
        
        
    }//GEN-LAST:event_formWindowActivated

    private void ciudadBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciudadBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ciudadBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAgregarInvestigador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAgregarInvestigador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAgregarInvestigador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAgregarInvestigador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAgregarInvestigador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField calleText;
    private javax.swing.JComboBox<Item> categoriaBox;
    private javax.swing.JComboBox<Item> centroDeInvestigacionBox;
    private javax.swing.JComboBox<Item> ciudadBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nombreinvText;
    private javax.swing.JTextField numText;
    private javax.swing.JComboBox<Item> rolBox;
    private javax.swing.JTextField rutText;
    private javax.swing.JComboBox<Item> universidadBox;
    // End of variables declaration//GEN-END:variables
}
