package GUI.EditarEliminar.Investigador;

import GUI.AGREGAR.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JComboBox;

import Clases.Item;
import GUI.MenuPrincipal;
import javax.swing.DefaultListModel;
/**
 *
 * @author Felipe
 */
public class FormEditarInvestigador extends javax.swing.JFrame {

    private static FormEditarInvestigador instancia;
    private String rutInv;
    
    public FormEditarInvestigador(String rut) {
        initComponents();
        rutInv = rut;
    }
    
    public static FormEditarInvestigador getInstancia(String rut) {
        if(instancia == null)
        {
            instancia = new FormEditarInvestigador(rut);
        }
        
        return instancia;
    }
    
    
    // retorna una instancia nueva
    public static FormEditarInvestigador getInstanciaNueva(String rut) {
        
        instancia = new FormEditarInvestigador(rut);      
        return instancia;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jFrame1 = new javax.swing.JFrame();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        rutText = new javax.swing.JTextField();
        nombreinvText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        calleText = new javax.swing.JTextField();
        numText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ciudadBox = new javax.swing.JComboBox<>();
        categoriaBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        modelo2 = new DefaultListModel();
        listaCIs = new javax.swing.JList<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        agregaCentro = new javax.swing.JButton();
        eliminaCentro = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        modelo3 = new DefaultListModel();
        listaUniversidad = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel11.setText("jLabel11");

        jLabel12.setText("jLabel12");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addContainerGap(355, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel11)
                .addGap(30, 30, 30)
                .addComponent(jLabel12)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        rutText.setEditable(false);
        rutText.setBackground(new java.awt.Color(204, 204, 255));
        rutText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rutTextActionPerformed(evt);
            }
        });

        jButton1.setText("Editar investigador");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("RUT");

        jLabel2.setText("Nombre");

        jLabel4.setText("Categoría");

        jLabel5.setText("Calle");

        jLabel6.setText("Número");

        jLabel7.setText("Centros de investigación en que trabaja");

        jLabel10.setText("Ciudad");

        ciudadBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciudadBoxActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Editar investigador");

        listaCIs.setModel(modelo2);
        jScrollPane1.setViewportView(listaCIs);

        jLabel13.setText("Centro");

        jLabel14.setText("Rol");

        agregaCentro.setText("Asociar a centro");
        agregaCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregaCentroActionPerformed(evt);
            }
        });

        eliminaCentro.setText("Desvincular de centro");
        eliminaCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminaCentroActionPerformed(evt);
            }
        });

        listaUniversidad.setModel(modelo3);
        jScrollPane2.setViewportView(listaUniversidad);

        jLabel8.setText("Universidades a las que está asociado");

        jButton2.setText("Asociar a universidad");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Desvincular de universidad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rutText, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 605, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ciudadBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 213, Short.MAX_VALUE)
                                .addComponent(categoriaBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(nombreinvText, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(calleText, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numText, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addGap(142, 142, 142)
                                                .addComponent(jLabel14)))
                                        .addGap(96, 96, 96))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(eliminaCentro, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                            .addComponent(agregaCentro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(56, 56, 56))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(86, 86, 86))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGap(109, 109, 109))))))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(rutText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nombreinvText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(ciudadBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(agregaCentro)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eliminaCentro)
                    .addComponent(jLabel4)
                    .addComponent(categoriaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(calleText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(numText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(52, 52, 52)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String rut = rutText.getText();
        try{
            
            MenuPrincipal.Conexion();
       
            // TABLAS DE INVESTIGADOR
            
            String nombreinv = nombreinvText.getText();                      
                       
            String calle = calleText.getText();            
            int num = Integer.parseInt(numText.getText());  
            
            // ciudad en la que vive el investigador
            String codigociudad = ((Item)ciudadBox.getSelectedItem()).getIdString();
            
            // categoría del investigador
            String codigocategoria = ((Item)categoriaBox.getSelectedItem()).getIdString();
            
            Statement s = MenuPrincipal.connection.createStatement();
            
            //edita investigador con los datos proporcionados
            int z = s.executeUpdate("UPDATE INVESTIGADOR SET RUT='"
            +rut+"', nombreInvestigador='"+nombreinv+"', codigociudad="+codigociudad+", codigocategoria="+codigocategoria+", calle='"+calle+"', num="+num+
                    "where rut='"+rut+"'");
                      
            
            if(z == 1){ JOptionPane.showMessageDialog(this, "Se editó el investigador exitosamente");  }
            
            
        } catch(SQLException e){
                 
            System.out.println(e.getSQLState());
                 if(e.getSQLState().equals("23505"))
                 {
                     JOptionPane.showMessageDialog(this, "No se puede agregar la investigadora(o) debido a que ya existe una(o) con el rut: "
                     + rut);
                 }  
                 else if(e.getSQLState().equals("42703"))
                 {
                     JOptionPane.showMessageDialog(this, "Número telefónico inválido, por favor ingrese un número sin puntos ni otros caracteres");
                 }  
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rutTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rutTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rutTextActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
        try{
            
            MenuPrincipal.Conexion();  
            Statement s = MenuPrincipal.connection.createStatement();
            modelo2.clear();
             ResultSet resultCI = s.executeQuery("SELECT c.nombre, r.descripcionRol FROM CENTRODEINVESTIGACION c, TRABAJACI t, ROL r "
                     + "where (t.codigoRol=r.codigoRol AND t.codigoCI=c.codigoCI AND t.RUT='"+rutInv+"')");
            while(resultCI.next())
            {
                   modelo2.addElement(resultCI.getString("nombre")+"     -     "+resultCI.getString("descripcionRol"));
            }  
            
            
            
    
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e);
        }
        
    }//GEN-LAST:event_formWindowActivated

    private void ciudadBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciudadBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ciudadBoxActionPerformed

    private void agregaCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregaCentroActionPerformed
        FormEditarInvestigadorAgregarCI ventanita = FormEditarInvestigadorAgregarCI.getInstancia(rutInv);
        ventanita.setVisible(true);
    }//GEN-LAST:event_agregaCentroActionPerformed

    private void eliminaCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminaCentroActionPerformed
        FormEditarInvestigadorEliminarCI ventanita = FormEditarInvestigadorEliminarCI.getInstancia(rutInv);
        ventanita.setVisible(true);
    }//GEN-LAST:event_eliminaCentroActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        FormEditarInvestigadorAgregarUniversidad ventanita = FormEditarInvestigadorAgregarUniversidad.getInstancia(rutInv);
        ventanita.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowStateChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         try{
            MenuPrincipal.Conexion();  
            Statement s = MenuPrincipal.connection.createStatement();
            
            // ENCUENTRA DATOS PREVIOS DEL INVESTIGADOR
            ResultSet resultInv = s.executeQuery("SELECT nombreInvestigador, codigociudad"
                    + ", codigocategoria, calle, num FROM INVESTIGADOR where(rut="+"'"+rutInv+"'"+")");
            rutText.setText(rutInv);
            while(resultInv.next()){
                nombreinvText.setText(resultInv.getString("nombreInvestigador"));
                calleText.setText(resultInv.getString("calle"));
                numText.setText(resultInv.getString("num"));
            }
            
            
            
            // AGREGA OPCIONES AL COMBOBOX DE CIUDAD
            ciudadBox.removeAllItems();
            ResultSet resultCiudad = s.executeQuery("SELECT nombreciudad, codigociudad FROM CIUDAD");
            while(resultCiudad.next())
            {
                ciudadBox.addItem(new Item(resultCiudad.getString("codigociudad"), resultCiudad.getString("nombreciudad")));
            }   
            // PRESELECCIONA CIUDAD
            ResultSet resultCiudadSel= s.executeQuery("SELECT codigociudad FROM INVESTIGADOR where "
                    + "rut='"+rutInv+"'");
            while(resultCiudadSel.next())
            {
                for(int i=0; i<ciudadBox.getItemCount(); i++)
                {
                    if(ciudadBox.getItemAt(i).getIdString() == null ? resultCiudadSel.getString("codigociudad") == null : ciudadBox.getItemAt(i).getIdString().equals(resultCiudadSel.getString("codigociudad")))
                    {
                        ciudadBox.setSelectedIndex(i);
                        
                    }
                }
            } 
            
            // AGREGA OPCIONES AL COMBOBOX DE CATEGORÍA
            categoriaBox.removeAllItems();
            ResultSet resultCategoría = s.executeQuery("SELECT codigocategoria, descripcioncategoría FROM categoria");
            while(resultCategoría.next())
            {
                categoriaBox.addItem(new Item(resultCategoría.getString("codigocategoria"), resultCategoría.getString("descripcioncategoría")));
            }
            
           
            // AGREGA CENTROS AL LISTADO DE CI QUE PERTENECE EL INVESTIGADOR
            
            modelo2.clear();
             ResultSet resultCI = s.executeQuery("SELECT c.nombre, r.descripcionRol FROM CENTRODEINVESTIGACION c, TRABAJACI t, ROL r "
                     + "where (t.codigoRol=r.codigoRol AND t.codigoCI=c.codigoCI AND t.RUT='"+rutInv+"')");
            while(resultCI.next())
            {
                   modelo2.addElement(resultCI.getString("nombre")+"     -     "+resultCI.getString("descripcionRol"));
            }           
            
            
            /*
            centroDeInvestigacionBox.addItem(new Item(0, "No asociar ningún centro"));
            while(resultCI.next())
            {
                centroDeInvestigacionBox.addItem(new Item(Integer.parseInt(resultCI.getString("codigoCI")), resultCI.getString("nombre")));
                
            }
            */
            
            /*
            //AGREGA OPCIONES AL COMBOBOX DE ROL EN CENTRO DE INVESTIGACIÓN
            s = MenuPrincipal.connection.createStatement();
            ResultSet resultRol = s.executeQuery("SELECT codigorol, descripcionrol FROM rol");
            while(resultRol.next())
            {
                rolBox.addItem(new Item(Integer.parseInt(resultRol.getString("codigorol")), resultRol.getString("descripcionrol")));
            }
            */
            
            
            // AGREGA LAS UNIVERSIDADES A LAS QUE EL INVESTIGADOR PERTENECE AL LISTA UNIVERSIDAD
            modelo3.clear();
            ResultSet resultUniversidad = s.executeQuery("SELECT u.nombre FROM UNIVERSIDAD u, PERTENECEUNIVERSIDAD p"
                    + " where p.rut='"+rutInv+"' AND u.codigouniversidad=p.codigouniversidad");
            while(resultUniversidad.next())
            {
                modelo3.addElement(resultUniversidad.getString("nombre"));
            }
            
            
            
        
        }
        catch(Exception e){
                    JOptionPane.showMessageDialog(this, e.getMessage());    
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEditarInvestigador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEditarInvestigador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEditarInvestigador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEditarInvestigador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregaCentro;
    private javax.swing.JTextField calleText;
    private javax.swing.JComboBox<Item> categoriaBox;
    private javax.swing.JComboBox<Item> ciudadBox;
    private javax.swing.JButton eliminaCentro;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaCIs;
    private DefaultListModel modelo2, modelo3;
    private javax.swing.JList<String> listaUniversidad;
    private javax.swing.JTextField nombreinvText;
    private javax.swing.JTextField numText;
    private javax.swing.JTextField rutText;
    // End of variables declaration//GEN-END:variables
}
